site_name: Documentação - Risco Socioambiental
site_author: Luiz Pascoal e Fernanda Stefani

theme: 'readthedocs'

nav:
  - 'HOME': 'index.md'
  - 'Guia do usuário':
    - 'Dados Geográficos': '01-guia_dados_geograficos.md'
    - 'Funcionalidades': '01-guia_funcionalidades.md'

  - 'Dados':
    - 'Banco de Dados': '03-banco_de_dados.md'

  - 'Arquitetura de Software':
    - 'Visão geral': '02-arq_geral.md'
    - 'Servidor de mapas': '02-arq_servidor_de_mapas.md'
    - 'Servidor de aplicação': '02-arq_servidor_de_aplicacao.md'
    - 'Deployment da arquitetura do Riscosocioambiental': '02-arq_execucao_risco.md'
